package com.example.server.web;

import com.example.server.auth.AuthService.LoginLockStatus;

public final class LoginPageRenderer {

    private LoginPageRenderer() {
    }

    public static String render(String alertMessage, LoginLockStatus lockStatus, String version) {
        String safeAlert = alertMessage == null ? "" : alertMessage;
        boolean locked = lockStatus.isLocked();
        int remainingSec = lockStatus.remainingSec;
        return ""
                + "<!DOCTYPE html>\n"
                + "<html lang=\"zh-TW\">\n"
                + "<head>\n"
                + "  <meta charset=\"UTF-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "  <title>PunchClock · 管理員登入</title>\n"
                + "  <link rel=\"stylesheet\" href=\"/css/login.css\">\n"
                + "</head>\n"
                + "<body>\n"
                + "  <nav class=\"site-navbar\" aria-label=\"主選單\">\n"
                + "    <div class=\"site-navbar-inner\">\n"
                + "      <div class=\"navbar-brand-text\">PunchClock 打卡工具 · v" + version + "</div>\n"
                + "    </div>\n"
                + "  </nav>\n"
                + "\n"
                + "  <div class=\"site-banner\">\n"
                + "    <h1 class=\"header-title\">遠端打卡監控控制台</h1>\n"
                + "    <p class=\"header-sub\">管理員登入</p>\n"
                + "  </div>\n"
                + "\n"
                + "  <section class=\"sec-login\">\n"
                + "    <div class=\"login-panel\">\n"
                + "      <div class=\"login-inner\">\n"
                + safeAlert
                + "        <form action=\"/login\" method=\"POST\" class=\"form-signin\">\n"
                + "          <div class=\"form-group\">\n"
                + "            <label for=\"password\">密碼</label>\n"
                + "            <div class=\"pwd-wrapper\">\n"
                + "              <input type=\"password\" id=\"password\" name=\"password\" class=\"form-input\" placeholder=\"請輸入管理員密碼\" required autofocus "
                + (locked ? "disabled" : "") + " />\n"
                + "              <button type=\"button\" id=\"togglePwdBtn\" class=\"btn-toggle-pwd\" onclick=\"togglePasswordVisibility()\" title=\"顯示/隱藏密碼\">顯示</button>\n"
                + "            </div>\n"
                + "          </div>\n"
                + "          <button type=\"submit\" id=\"btnSubmit\" class=\"btn-submit\" "
                + (locked ? "disabled" : "") + ">" + (locked ? "冷卻鎖定中…" : "登入") + "</button>\n"
                + "        </form>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </section>\n"
                + "\n"
                + "  <footer class=\"site-footer\">PunchClock 管理後台 · 樣式參考臺北市校務行政系統入口</footer>\n"
                + "\n"
                + "  <script>\n"
                + "    function togglePasswordVisibility() {\n"
                + "      const pwdInput = document.getElementById('password');\n"
                + "      const toggleBtn = document.getElementById('togglePwdBtn');\n"
                + "      if (pwdInput.type === 'password') {\n"
                + "        pwdInput.type = 'text';\n"
                + "        toggleBtn.textContent = '隱藏';\n"
                + "      } else {\n"
                + "        pwdInput.type = 'password';\n"
                + "        toggleBtn.textContent = '顯示';\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    let remainingSec = " + remainingSec + ";\n"
                + "    if (remainingSec > 0) {\n"
                + "      const timerSpan = document.getElementById('countdown');\n"
                + "      const submitBtn = document.getElementById('btnSubmit');\n"
                + "      const passwordInput = document.getElementById('password');\n"
                + "      const lockAlert = document.getElementById('lockAlert');\n"
                + "\n"
                + "      const interval = setInterval(() => {\n"
                + "        remainingSec--;\n"
                + "        if (remainingSec > 0) {\n"
                + "          const mins = Math.floor(remainingSec / 60);\n"
                + "          const secs = remainingSec % 60;\n"
                + "          if (timerSpan) {\n"
                + "            timerSpan.textContent = mins > 0 ? `${mins} 分 ${secs} 秒` : `${secs} 秒`;\n"
                + "          }\n"
                + "        } else {\n"
                + "          clearInterval(interval);\n"
                + "          if (passwordInput) passwordInput.disabled = false;\n"
                + "          if (submitBtn) {\n"
                + "            submitBtn.disabled = false;\n"
                + "            submitBtn.textContent = '登入';\n"
                + "          }\n"
                + "          if (lockAlert) {\n"
                + "            lockAlert.style.display = 'none';\n"
                + "          }\n"
                + "        }\n"
                + "      }, 1000);\n"
                + "    }\n"
                + "  </script>\n"
                + "</body>\n"
                + "</html>\n";
    }
}
